image: Ubuntu2204

stack: node 20

branches:
  only:
    - video

cache:
  - node_modules

install:
  - yarn install

build: false

build_script:
  - yarn build

test_script:
  - yarn lint
  - yarn test

deploy_script:
  # Настройка Git для деплоя подпапки
  - git config --global user.name AppVeyor
  - git config --global user.email ci@appveyor.com
  - git config --global credential.helper store
  - echo "https://$GITHUB_TOKEN:x-oauth-basic@github.com" > "$HOME/.git-credentials"
  # Деплой только папки events из общего репозитория
  - npx gh-pages -d events/dist -u "appveyor-bot <ci@appveyor.com>" -e events