image: Ubuntu2204  # образ для сборки

stack: node 20  # окружение

branches:
  only:
    - master  # ветка git
    - main

cache:
  - node_modules  # кеширование

install:
  - npm install  # команда установки зависимостей

build: false  # отключаем встроенную в appveyor систему сборки

build_script:
  - npm run build   # команда сборки

test_script:
  - npm run lint
  - npm test  # скрипт тестирования

# Если проект в отдельном репозитории, но т к я его храню в общем репозитории, то это не использую
deploy_script:
  - git config --global credential.helper store
  - git config --global user.name AppVeyor
  - git config --global user.email ci@appveyor.com
  - echo "https://$GITHUB_TOKEN:x-oauth-basic@github.com" > "$HOME/.git-credentials"
  - npx gh-pages -d dist -u "appveyor-bot <ci@appveyor>"