name: Deploy Apps

on:
  workflow_dispatch:

  push:
    branches:
      - video
    paths:
      - 'events/**'
      - 'anim/**'
      - 'dnd/**'
      - 'docs/**'
      - 'dom/**'
      - 'env/**'
      - 'forms/**'
      - 'http/**'
      - 'media/**'
      - 'rxjs/**'
      - 'sse-ws/**'
      - 'workers/**'
      - 'testing/**'
      - 'yarn-cd/**'

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [events, anim, dnd, docs, dom, env, forms, http, media, rxjs, sse-ws, workers, testing, yarn-cd]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: video
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'
      
      - name: Setup Yarn
        run: npm install -g yarn@1.22.19

      - name: Clean Install
        working-directory: ${{ matrix.project }}
        run: |
          rm -rf node_modules
          rm -f yarn.lock
          yarn install --no-lockfile --network-timeout 1000000
        env:
          CI: false
          NODE_OPTIONS: "--max-old-space-size=8192"
        timeout-minutes: 30

      - name: Build
        working-directory: ${{ matrix.project }}
        run: yarn build
        if: success()

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ${{ matrix.project }}/dist
          target-folder: ${{ matrix.project }}
          branch: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}
