name: Deploy Apps

on:
  workflow_dispatch:

  push:
    branches: 
      - video
    paths:
      - 'events/**'
      - 'anim/**'
      - 'dnd/**'
      - 'docs/**'
      - 'dom/**'
      - 'env/**'
      - 'forms/**'
      - 'http/**'
      - 'media/**'
      - 'rxjs/**'
      - 'sse-ws/**'
      - 'workers/**'
      - 'testing/**'
      - 'yarn-cd/**'

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    strategy:
      matrix:
        project: [events, anim, dnd, docs, dom, env, forms, http, media, rxjs, sse-ws, workers, testing, yarn-cd]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./${{ matrix.project }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
          cache-dependency-path: ./${{ matrix.project }}/yarn.lock

      - name: Install dependencies
        run: |
          yarn config set network-timeout 300000
          yarn install --frozen-lockfile --prefer-offline
        continue-on-error: true
        env:
          CI: true
        timeout-minutes: 15

      - name: Build
        run: yarn build
        if: success()

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ${{ matrix.project }}/dist
          target-folder: ${{ matrix.project }}
          branch: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}
